version: "3.8"

services:
  servicewatch_app:
    image: ernestodota2011/servicewatch:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - generalnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.servicewatch.rule=Host(`servicewatch.aetherlogik.com`)"
      - "traefik.http.routers.servicewatch.entrypoints=websecure"
      - "traefik.http.routers.servicewatch.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.servicewatch.loadbalancer.server.port=80"
      - "traefik.http.services.servicewatch.loadbalancer.passHostHeader=true"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  generalnet:
    external: true
    name: generalnet
