version: "3.8"

services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=servicewatch
    networks:
      - generalnet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  servicewatch:
    image: ernestodota2011/servicewatch:latest
    networks:
      - generalnet
    depends_on:
      - mongodb
    volumes:
      - servicewatch_data:/app/data
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/servicewatch
      - API_BASE_URL=https://api.servicewatch.aetherlogik.com/v1
    deploy:
      replicas: 1
      update_config:
        order: stop-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.servicewatch.rule=Host(`servicewatch.aetherlogik.com`)"
        - "traefik.http.routers.servicewatch.entrypoints=websecure"
        - "traefik.http.routers.servicewatch.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.servicewatch.loadbalancer.server.port=80"
        - "traefik.http.services.servicewatch.loadbalancer.passHostHeader=true"

networks:
  generalnet:
    external: true
    name: generalnet

volumes:
  mongodb_data:
  servicewatch_data: