version: "3.8"

services:
  servicewatch_app:
    image: ernestodota2011/servicewatch:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - generalnet
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.servicewatch.rule=Host(`servicewatch.aetherlogik.com`)"
      - "traefik.http.routers.servicewatch.entrypoints=websecure"
      - "traefik.http.routers.servicewatch.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.servicewatch.loadbalancer.server.port=80"
      - "traefik.http.services.servicewatch.loadbalancer.passHostHeader=true"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  generalnet:
    external: true
    name: generalnet
